"""
helpers.py
------------------------------------------------------------------
General-purpose helper functions used across multiple GUI pages:

    - Date/time formatting
    - Score formatting and color coding (wraps config.py helpers)
    - CSV export
    - PDF export (best-effort, using matplotlib as a lightweight
      PDF renderer so no extra heavy PDF library is required)
------------------------------------------------------------------
"""

import csv
import os
from datetime import datetime

import config


def format_date(raw_date_string, output_format="%b %d, %Y"):
    """
    Converts a stored 'YYYY-MM-DD HH:MM:SS' date string into a
    friendly display format like 'Jul 21, 2026'.

    Args:
        raw_date_string (str): date string as stored in SQLite.
        output_format (str): desired strftime output format.

    Returns:
        str: formatted date, or the original string if parsing fails.
    """
    if not raw_date_string:
        return "N/A"
    try:
        parsed_date = datetime.strptime(raw_date_string, "%Y-%m-%d %H:%M:%S")
        return parsed_date.strftime(output_format)
    except ValueError:
        return raw_date_string


def truncate_text(text, max_length=80):
    """Shortens long text for table display, appending '...' if cut."""
    if not text:
        return ""
    text = text.strip().replace("\n", " ")
    if len(text) <= max_length:
        return text
    return text[:max_length].rstrip() + "..."


def format_score(score):
    """Formats a numeric match score for display, e.g. 84.5 -> '84.5%'."""
    try:
        return f"{float(score):.1f}%"
    except (TypeError, ValueError):
        return "0.0%"


def generate_export_filename(prefix, extension):
    """
    Builds a timestamped export filename so repeated exports never
    overwrite each other, e.g. 'candidates_report_20260721_143210.csv'.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{prefix}_{timestamp}.{extension}"


def export_to_csv(rows, column_headers, filename):
    """
    Exports a list of dictionaries (or lists) to a CSV file inside
    the application's exports/ folder.

    Args:
        rows (list[dict]): the data rows to export.
        column_headers (list[str]): keys (for dicts) / column titles.
        filename (str): desired output file name (e.g. 'report.csv').

    Returns:
        str: full path to the exported file.
    """
    export_path = os.path.join(config.EXPORT_DIR, filename)

    with open(export_path, mode="w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(column_headers)

        for row in rows:
            if isinstance(row, dict):
                writer.writerow([row.get(header, "") for header in column_headers])
            else:
                writer.writerow(row)

    return export_path


def export_to_pdf(title, rows, column_headers, filename):
    """
    Exports tabular data to a simple, clean PDF report using
    matplotlib's PDF backend (PdfPages). This avoids requiring a
    heavyweight external PDF library while still producing a real,
    presentable PDF document - appropriate for a student project.

    Args:
        title (str): report title shown at the top of the PDF.
        rows (list[dict]): data rows to include in the table.
        column_headers (list[str]): dictionary keys / column titles.
        filename (str): desired output file name (e.g. 'report.pdf').

    Returns:
        str: full path to the exported PDF file.
    """
    import matplotlib
    matplotlib.use("Agg")  # non-interactive backend, safe for file export
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages

    export_path = os.path.join(config.EXPORT_DIR, filename)

    # Convert dict rows into simple table rows matching column_headers
    table_data = []
    for row in rows:
        if isinstance(row, dict):
            table_data.append([str(row.get(header, "")) for header in column_headers])
        else:
            table_data.append([str(value) for value in row])

    rows_per_page = 20
    total_pages = max(1, (len(table_data) + rows_per_page - 1) // rows_per_page)

    with PdfPages(export_path) as pdf_document:
        for page_number in range(total_pages):
            figure, axis = plt.subplots(figsize=(11.7, 8.3))  # A4 landscape
            axis.axis("off")

            figure.suptitle(title, fontsize=16, fontweight="bold", color="#0B3D2E")
            axis.text(
                0.0, 1.02,
                f"Generated by {config.APP_NAME}  |  "
                f"{datetime.now().strftime('%B %d, %Y %H:%M')}  |  "
                f"Page {page_number + 1} of {total_pages}",
                transform=axis.transAxes, fontsize=8, color="#64748B"
            )

            page_rows = table_data[
                page_number * rows_per_page: (page_number + 1) * rows_per_page
            ]

            if page_rows:
                table = axis.table(
                    cellText=page_rows,
                    colLabels=column_headers,
                    loc="center",
                    cellLoc="left",
                )
                table.auto_set_font_size(False)
                table.set_fontsize(8)
                table.scale(1, 1.5)

                # Style header row
                for col_index in range(len(column_headers)):
                    header_cell = table[0, col_index]
                    header_cell.set_facecolor("#059669")
                    header_cell.set_text_props(color="white", fontweight="bold")

            pdf_document.savefig(figure)
            plt.close(figure)

    return export_path


def open_file_location(file_path):
    """
    Opens the folder containing the exported file in the system's
    default file explorer (cross-platform best-effort).
    """
    folder_path = os.path.dirname(file_path)
    try:
        if os.name == "nt":
            os.startfile(folder_path)
        elif os.name == "posix":
            os.system(f'xdg-open "{folder_path}" 2>/dev/null || open "{folder_path}"')
    except Exception:
        pass  # Non-critical convenience feature; safe to ignore failures
